name: Run Selenium UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Maven Dependencies
        run: mvn clean install -DskipTests

      - name: Run UI Tests
        run: mvn test -DsuiteXmlFile=testng.xml
