name: 🧪 Run UI Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master   # Or main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:114.0
        ports:
          - 4444:4444
        options: >-
          --shm-size 2g
          --name selenium-hub

    env:
      CHROME_OPTS: "--headless --no-sandbox --disable-dev-shm-usage"

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: ☕ Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 📦 Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: 🧪 Run UI Tests with Maven
        run: mvn clean test "-DsuiteXmlFile=testng.xml"
